name: training tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    # install a specific version of Node using
    # https://github.com/actions/setup-node
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
    # Restore the previous npm modules and Cypress binary archives.
    # In case there's no previous cache the packages will be downloaded
    # and saved automatically after the entire workflow successfully finishes.
    # See https://github.com/actions/cache
    - name: Cache node modules
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
    - name: Cache Cypress binary
      uses: actions/cache@v4
      with:
        path: ~/.cache/Cypress
        key: cypress-${{ runner.os }}-cypress-${{ hashFiles('**/package-lock.json') }}
    - name: install dependencies and verify Cypress
      env:
        # make sure every Cypress install prints minimal information
        CI: 1
      # print Cypress and OS info
      run: |
        npm ci
        npx cypress verify
        npx cypress info
        npx cypress version
        npx cypress version --component package
        npx cypress version --component binary
        npx cypress version --component electron
        npx cypress version --component node
